[{"bug_type":"USE_AFTER_FREE","qualifier":"pointer `x` last assigned on line 6 was freed by call to `free()` at line 11, column 5 and is dereferenced or freed at line 12, column 5.","severity":"ERROR","line":12,"column":5,"procedure":"main","procedure_start_line":4,"file":"access_freed.c","bug_trace":[{"level":0,"filename":"access_freed.c","line_number":4,"column_number":1,"description":"start of procedure main()"},{"level":0,"filename":"access_freed.c","line_number":6,"column_number":5,"description":""},{"level":0,"filename":"access_freed.c","line_number":7,"column_number":9,"description":"Taking false branch"},{"level":0,"filename":"access_freed.c","line_number":10,"column_number":5,"description":""},{"level":0,"filename":"access_freed.c","line_number":11,"column_number":5,"description":""},{"level":0,"filename":"access_freed.c","line_number":12,"column_number":5,"description":""}],"key":"access_freed.c|main|USE_AFTER_FREE","node_key":"afa64f7520584b9b96ea71619c81c804","hash":"0b03534399fa1e92091f598487b07f4e","bug_type_hum":"Use After Free"}]
